const {test}=require('node:test');const assert=require('node:assert/strict');const {chromium}=require('playwright');
const path=require('node:path');const fs=require('node:fs');const http=require('node:http');
const root=path.resolve(__dirname,'../public');
let browser,server,base;
test.before(async()=>{server=http.createServer((req,res)=>{let f=path.join(root,new URL(req.url,'http://x').pathname);if(f.endsWith('/'))f+='index.html';try{const ext=path.extname(f);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg'})[ext]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({headless:true,executablePath:process.env.CAHK_TEST_BROWSER||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});});
test.after(async()=>{await browser?.close();await new Promise(r=>server?.close(r));});
async function page(){const p=await browser.newPage({viewport:{width:390,height:844}});await p.route('**/functions/v1/cahk-denuncias**',route=>route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({protocol:'CAHK-17'})}));return p;}
test('home replaces install call to action with report navigation',async()=>{const p=await page();await p.goto(base);assert.equal(await p.getByRole('link',{name:'Fazer uma denúncia',exact:true}).count(),1);assert.equal(await p.getByRole('button',{name:'Instalar CAHK como aplicativo'}).count(),0);await p.close();});
test('report form has no identity fields, preserves failed text and confirms persisted receipt',async()=>{const p=await page();await p.goto(base+'/denuncias/');assert.equal(await p.locator('input[type=email],input[name=nome],input[name=email]').count(),0);await p.screenshot({path:path.resolve(__dirname,'../docs/form-mobile.png'),fullPage:true});await p.locator('#reportText').fill('Descrição da situação com mais de vinte caracteres.');await p.route('**/functions/v1/cahk-denuncias**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"Falha temporária"}'}));await p.locator('#reportConsent').check();await p.getByRole('button',{name:'Enviar denúncia',exact:true}).click();await p.locator('#formMessage').filter({hasText:'Falha temporária'}).waitFor();assert.match(await p.locator('#reportText').inputValue(),/Descrição/);assert.equal(await p.locator('#receipt').isVisible(),false);await p.unroute('**/functions/v1/cahk-denuncias**');await p.route('**/functions/v1/cahk-denuncias**',r=>r.fulfill({status:201,contentType:'application/json',body:'{"protocol":"CAHK-17"}'}));await p.locator('#reportConsent').check();await p.getByRole('button',{name:'Enviar denúncia',exact:true}).click();await p.locator('#receipt').waitFor({state:'visible'});assert.equal(await p.locator('#receiptCode').textContent(),'CAHK-17');assert.equal(await p.locator('#reportText').inputValue(),'');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:path.resolve(__dirname,'../docs/form-success.png'),fullPage:true});await p.close();});
test('selected photograph becomes a JPEG without original filename in the request',async()=>{const p=await page();let payload;await p.unroute('**/functions/v1/cahk-denuncias**');await p.route('**/functions/v1/cahk-denuncias**',async r=>{payload=r.request();await r.fulfill({status:201,contentType:'application/json',body:'{"protocol":"CAHK-18"}'});});await p.goto(base+'/denuncias/');await p.locator('#reportText').fill('Relato com imagem opcional em anexo para a gestão.');const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4mQAAAAASUVORK5CYII=','base64');await p.locator('#reportImages').setInputFiles({name:'nome-identificavel.png',mimeType:'image/png',buffer:image});await p.locator('#imagePreview img').waitFor();await p.locator('#reportConsent').check();await p.getByRole('button',{name:'Enviar denúncia',exact:true}).click();await p.locator('#receipt').waitFor({state:'visible'});assert.equal(payload.headers()['authorization'],undefined);assert.ok(!payload.postDataBuffer().includes(Buffer.from('nome-identificavel')));assert.ok(payload.postDataBuffer().includes(Buffer.from('image/jpeg')));await p.close();});
async function managementPage({snapshot=true,failRefresh=false}={}){
 const p=await browser.newPage({viewport:{width:1100,height:850}});let updates=0,details=0,release;
 await p.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:`window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'test-jwt'}}}),onAuthStateChange:()=>{}}})};`}));
 await p.route('**/gestao/app.js*',r=>r.fulfill({contentType:'text/javascript',body:snapshot?`window.CAHK_MANAGEMENT_PROFILE={ativo:true,role:'admin'};`:''}));
 await p.route('**/gestao/v6.js*',r=>r.fulfill({contentType:'text/javascript',body:''}));await p.route('**/gestao/news-admin.js*',r=>r.fulfill({contentType:'text/javascript',body:''}));
 await p.route('**/functions/v1/cahk-denuncias**',async r=>{
  const action=new URL(r.request().url()).searchParams.get('action');const row={id:'11111111-1111-4111-8111-111111111111',protocol:'CAHK-21',created_at:'2026-10-02T22:00:00Z',status:'recebida',version:1+updates,text:'<img src=x onerror=alert(1)> Relato de teste controlado.',internal_notes:updates?'Registro de providências.':''};
  let data,status=200;if(action==='list')data={items:[row],has_more:false};if(action==='detail'){details++;if(failRefresh&&details>1){status=503;data={error:'Atualização indisponível'};}else data={item:row,photos:[],history:[]};}
  if(action==='update'){await new Promise(resolve=>release=resolve);updates++;data={saved:true,version:2};}
  await r.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 });
 await p.goto(base+'/gestao/');await p.evaluate(()=>{document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');document.getElementById('view-dashboard').classList.add('hidden');document.getElementById('view-denuncias').classList.remove('hidden');});
 if(!snapshot)await p.evaluate(()=>window.dispatchEvent(new CustomEvent('cahk-profile-ready',{detail:{ativo:true,role:'admin'}})));
 return {p,release:()=>release?.()};
}
test('management loads when authentication completed before complaints script registered',async()=>{const {p}=await managementPage();await p.locator('#complaintNav').click();await p.locator('.complaint-row').waitFor({timeout:3000});assert.match(await p.locator('.complaint-row').textContent(),/CAHK-21/);await p.close();});
test('saving locks editor and keeps usable state when post-save refresh fails',async()=>{const {p,release}=await managementPage({snapshot:false,failRefresh:true});await p.locator('#complaintNav').click();await p.locator('.complaint-row').click();await p.locator('#complaintDetail').waitFor({state:'visible'});assert.equal(await p.locator('#complaintText img').count(),0);await p.locator('#complaintNotes').fill('Registro de providências.');await p.locator('#complaintSave').click();await p.locator('#complaintMessage').filter({hasText:'Salvando'}).waitFor();assert.equal(await p.locator('#complaintNotes').isDisabled(),true);assert.equal(await p.locator('#complaintStatus').isDisabled(),true);release();await p.locator('#complaintMessage').filter({hasText:'recarregar'}).waitFor({timeout:5000});assert.equal(await p.locator('#complaintNotes').inputValue(),'Registro de providências.');assert.equal(await p.locator('#complaintSave').isEnabled(),true);await p.screenshot({path:path.resolve(__dirname,'../docs/management.png'),fullPage:true});await p.close();});
test('management report and privacy notice stay readable in the light theme',async()=>{const {p}=await managementPage();await p.locator('#complaintNav').click();await p.locator('.complaint-row').click();await p.locator('#complaintDetail').waitFor({state:'visible'});const values=await p.evaluate(()=>{const selectors=['.complaint-notice','.complaint-text','.complaint-row strong','#complaintForm label'];return selectors.map(s=>{const e=document.querySelector(s),c=getComputedStyle(e);return {s,color:c.color,bg:c.backgroundColor};});});const text=values.find(v=>v.s==='.complaint-text');assert.notEqual(text.bg,'rgb(14, 17, 22)');assert.notEqual(values.find(v=>v.s==='.complaint-row strong').color,'rgb(245, 247, 250)');await p.close();});
